#!/usr/bin/env python3
"""
gallerybuild.py  —  Single script to build all gallery viewers.

Usage:
    python gallerybuild.py                    # default: E:/gallery
    python gallerybuild.py --gallery D:/gallery
    python gallerybuild.py am2 lca1           # only named books

Layout expected:
    E:/gallery/
      template.html              ← viewer template
      am2/                       ← book folder (any name)
        pages/                   ← required: contains page images
          page-001.webp
          page-002.webp
        toc.txt                  ← optional: pipe-delimited TOC
        viewer.html              ← OUTPUT: generated by this script
        index.json               ← OUTPUT: page list + metadata
"""

import os, sys, json, re, glob
from pathlib import Path

GALLERY_ROOT = Path(r"E:/gallery")
IMG_EXTS = {'.webp', '.png', '.jpg', '.jpeg'}


def natural_sort_key(s):
    return [int(c) if c.isdigit() else c.lower() for c in re.split(r'(\d+)', str(s))]


def find_books(gallery, only=None):
    """Find book folders (those containing a pages/ subdirectory)."""
    books = []
    for entry in sorted(gallery.iterdir()):
        if not entry.is_dir():
            continue
        if entry.name.startswith('.') or entry.name.lower() in ('__pycache__', 'misc', 'archive'):
            continue
        if (entry / 'pages').is_dir():
            if only is None or entry.name in only:
                books.append(entry)
    return books


def get_pages(book_dir):
    """Get sorted list of image filenames from pages/."""
    pages_dir = book_dir / 'pages'
    files = [f.name for f in pages_dir.iterdir()
             if f.is_file() and f.suffix.lower() in IMG_EXTS]
    files.sort(key=natural_sort_key)
    return files


def find_toc_file(book_dir):
    """Find the TOC .txt file in a book directory. Prefers toc.txt, falls back to any .txt."""
    toc_file = book_dir / 'toc.txt'
    if toc_file.exists():
        return toc_file
    txt_files = sorted(f for f in book_dir.iterdir() if f.suffix.lower() == '.txt' and f.is_file())
    return txt_files[0] if txt_files else None


def parse_toc(book_dir):
    """Parse pipe-delimited TOC from any .txt file into {chapters: [...]} structure."""
    toc_file = find_toc_file(book_dir)
    if not toc_file:
        return {"chapters": []}

    chapters = []
    current_chapter = None

    for line in toc_file.read_text(encoding='utf-8').splitlines():
        line = line.strip()
        if not line or line.startswith('#'):
            continue

        parts = [p.strip() for p in line.split('|')]
        kind = parts[0].upper()

        # Parse key=value pairs from remaining fields
        kv = {}
        positional = []
        for p in parts[1:]:
            if '=' in p:
                k, v = p.split('=', 1)
                kv[k.strip().lower()] = v.strip()
            else:
                positional.append(p)

        def safe_int(val, default=1):
            try: return int(val)
            except (ValueError, TypeError): return default

        if kind == 'CHAPTER':
            code = positional[0] if len(positional) > 0 else ''
            title = positional[1] if len(positional) > 1 else ''
            current_chapter = {
                "code": code,
                "title": title,
                "start": safe_int(kv.get('start'), 1),
                "end": safe_int(kv.get('end'), 0),
                "sections": []
            }
            chapters.append(current_chapter)

        elif kind == 'SECTION' and current_chapter is not None:
            code = positional[0] if len(positional) > 0 else ''
            title = positional[1] if len(positional) > 1 else ''
            current_chapter["sections"].append({
                "code": code,
                "title": title,
                "start": safe_int(kv.get('start'), 1),
                "end": safe_int(kv.get('end'), 0)
            })

    return {"chapters": chapters}


def build_viewer(book_dir, template_html):
    """Generate viewer.html and index.json for a single book."""
    book_name = book_dir.name
    pages = get_pages(book_dir)

    if not pages:
        print(f"  SKIP {book_name}: no images in pages/")
        return False

    toc = parse_toc(book_dir)

    # Read page offset from toc file header or default to 0
    page_offset = 0
    toc_file = find_toc_file(book_dir)
    if toc_file:
        for line in toc_file.read_text(encoding='utf-8').splitlines():
            line = line.strip()
            if line.upper().startswith('OFFSET'):
                parts = line.split('|')
                if len(parts) >= 2:
                    try:
                        page_offset = int(parts[1].strip())
                    except ValueError:
                        pass
                break

    # Build viewer.html from template
    html = template_html
    html = html.replace('__BOOK_NAME__', book_name)
    html = html.replace('__PAGES__', json.dumps(pages))
    html = html.replace("__IMG_BASE__", json.dumps("pages"))
    html = html.replace('__TOC__', json.dumps(toc))
    html = html.replace('__PAGE_OFFSET__', str(page_offset))

    viewer_path = book_dir / 'viewer.html'
    viewer_path.write_text(html, encoding='utf-8')

    # Build index.json
    index = {
        "book": book_name,
        "pages": pages,
        "pageCount": len(pages),
        "pageOffset": page_offset,
        "hasTOC": len(toc["chapters"]) > 0,
        "tocChapters": len(toc["chapters"])
    }
    index_path = book_dir / 'index.json'
    index_path.write_text(json.dumps(index, indent=2), encoding='utf-8')

    toc_src = find_toc_file(book_dir)
    toc_name = toc_src.name if toc_src else 'none'
    print(f"  OK   {book_name}: {len(pages)} pages, {len(toc['chapters'])} chapters ({toc_name}) → viewer.html")
    return True


def build_gallery_index(gallery, books):
    """Generate gallery/index.html listing all books."""
    entries = []
    for book_dir in books:
        idx_file = book_dir / 'index.json'
        if idx_file.exists():
            info = json.loads(idx_file.read_text(encoding='utf-8'))
        else:
            info = {"book": book_dir.name, "pageCount": 0, "hasTOC": False}
        # Thumbnail: first page image
        pages_dir = book_dir / 'pages'
        thumb = ''
        for f in sorted(pages_dir.iterdir(), key=lambda x: natural_sort_key(x.name)):
            if f.suffix.lower() in IMG_EXTS:
                thumb = f"{book_dir.name}/pages/{f.name}"
                break
        entries.append({**info, "thumb": thumb})

    html = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Gallery</title>
<style>
* { margin: 0; padding: 0; box-sizing: border-box; }
body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
       background: #1a1a1a; color: #e0e0e0; padding: 24px; }
h1 { font-size: 20px; margin-bottom: 20px; color: #fff; }
.grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(200px, 1fr)); gap: 16px; }
.card { background: #222; border: 1px solid #333; border-radius: 8px; overflow: hidden;
        cursor: pointer; transition: border-color 0.2s, transform 0.15s; }
.card:hover { border-color: #0066cc; transform: translateY(-2px); }
.card a { text-decoration: none; color: inherit; display: block; }
.card-thumb { width: 100%; aspect-ratio: 3/4; object-fit: cover; background: #111; display: block; }
.card-info { padding: 10px; }
.card-title { font-size: 14px; font-weight: 600; color: #fff; margin-bottom: 4px; }
.card-meta { font-size: 11px; color: #888; }
</style>
</head>
<body>
<h1>Gallery</h1>
<div class="grid">
"""
    for e in entries:
        toc_label = f" · {e.get('tocChapters', 0)} ch" if e.get('hasTOC') else ''
        thumb_tag = f'<img class="card-thumb" src="{e["thumb"]}" alt="">' if e['thumb'] else '<div class="card-thumb"></div>'
        html += f"""<div class="card"><a href="{e['book']}/viewer.html">
{thumb_tag}
<div class="card-info">
<div class="card-title">{e['book']}</div>
<div class="card-meta">{e.get('pageCount', 0)} pages{toc_label}</div>
</div></a></div>
"""
    html += "</div>\n</body>\n</html>"

    index_path = gallery / 'index.html'
    index_path.write_text(html, encoding='utf-8')
    print(f"  Gallery index: {len(entries)} books → index.html")


def main():
    gallery = GALLERY_ROOT
    only_books = None

    # Parse args
    args = sys.argv[1:]
    filtered = []
    i = 0
    while i < len(args):
        if args[i] == '--gallery' and i + 1 < len(args):
            gallery = Path(args[i + 1])
            i += 2
        else:
            filtered.append(args[i])
            i += 1

    if filtered:
        only_books = set(filtered)

    gallery = gallery.resolve()
    print(f"Gallery: {gallery}")

    # Load template
    template_path = gallery / 'template.html'
    if not template_path.exists():
        print(f"ERROR: template.html not found in {gallery}")
        sys.exit(1)
    template_html = template_path.read_text(encoding='utf-8')

    # Discover and build
    books = find_books(gallery, only_books)
    if not books:
        print("No book folders found (need pages/ subdirectory)")
        sys.exit(1)

    print(f"Found {len(books)} book(s)\n")
    ok = 0
    built = []
    for book in books:
        if build_viewer(book, template_html):
            ok += 1
            built.append(book)

    # Always rebuild gallery index with ALL books (not just filtered)
    all_books = find_books(gallery)
    build_gallery_index(gallery, all_books)

    print(f"\nDone: {ok}/{len(books)} built")


if __name__ == '__main__':
    main()
